services:
  frontend:
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
